#!/bin/bash

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export NVM_DIR="/home/tmiranda/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Path to the bash it configuration
export BASH_IT="/home/tmiranda/.bash_it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='bobby'

# (Advanced): Change this to the name of your remote repo if you
# cloned bash-it with a remote other than origin such as `bash-it`.
# export BASH_IT_REMOTE='bash-it'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/xvzf/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# Load Bash It
source $BASH_IT/bash_it.sh

###
#  _____ ____ __  __ ____            _
# |_   _/ ___|  \/  | __ )  __ _ ___| |__
#   | || |   | |\/| |  _ \ / _` / __| '_ \
#   | || |___| |  | | |_) | (_| \__ \ | | |
#   |_| \____|_|  |_|____/ \__,_|___/_| |_|

##
# Variables
ME="Tiago Miranda"
MAIL="tgcvmr@gmail.com"

BEEP="/usr/share/sounds/gnome/default/alerts/drip.ogg"

##
# Helpers
command_exists () { type "$1" &> /dev/null ; }

##
# Paths
export PKG_CONFIG_PATH=/usr/include/;

# Use with cordova
export ANDROID_HOME=/home/tmiranda/dev/android-sdk-linux
export JAVA_HOME=/home/tmiranda/dev/jdk

# Exports
export PATH=$PATH:/home/tmiranda/.composer/vendor/bin/;
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export PATH=$PATH:$JAVA_HOME/bin
export PATH=$PATH:/usr/local/bin

export EDITOR='emacs'
export TERM=xterm-256color

##
# Alias
alias rm='rm -I ';
alias ll='ls -lahB --color --group-directories-first';

alias mkdots='cp ~/myenv/.editorconfig . && cp ~/myenv/.gitignore .';

alias beep='paplay $BEEP';
alias xterm='xterm -bg rgb:22/22/22';

alias ssh.link.fossil='ssh -L 9100:localhost:9100 tiago@home.vikingmakt.com.br -p 12000';

alias cd.www='/var/www/html/';

alias tmux.n.dev='tmux new -s dev';
alias tmux.a.dev='tmux a -t dev';

alias s.php='sudo systemctl start nginx && sudo systemctl start php-fpm';

alias faux='ps -faux';

alias emacs='emacs-nox';
alias ed='emacs --daemon';
alias e='emacsclient -t';

alias wgeto="wget -qO- ";

# Servers
alias phpasdf="ssh root@phpasdf.ddns.net"
alias rethinkdev="ssh root@rethinkdev.ddns.net"
alias laleblu="ssh root@45.55.44.219"

# General
alias mybash.update="wget -qO- https://raw.githubusercontent.com/TCMiranda/BashConfig/master/install | bash"
